CREATE DATABASE IF NOT EXISTS mutual_funds;
USE mutual_funds;

CREATE TABLE IF NOT EXISTS funds (
    id INT AUTO_INCREMENT PRIMARY KEY,
    scheme_code VARCHAR(20) UNIQUE NOT NULL,
    last_nav FLOAT NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
